<?php
/**
 * @file
 * This file contains all Drupal hooks for the module other than any
 * node hooks and block hooks. Those go in the [module name].chado_node.inc file
 * and [module_name].blocks.inc respectively
 *
 * @ingroup legume_marker
 */

require_once('includes/legume_marker.chado_node.inc');
//require_once 'includes/legume_marker.marker_search.inc';
//require_once 'includes/legume_marker.views.inc';

function legume_marker_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'legume_marker');

  $items = array(
    'tripal_feature_marker_base' => array(
      'variables' => array('node' => NULL),
      'template' => 'tripal_feature_marker_base',
      'path' => "$path/theme/templates",
    ),

    'tripal_feature_marker_positions' => array(
      'variables' => array('node' => NULL),
      'template' => 'tripal_feature_marker_positions',
      'path' => "$path/theme/templates",
    ),

  );

  return $items;
}

/**
  * hook_form_alter
  *
  * Add a validator to the search form.
  */
function legume_marker_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'views_exposed_form' && strstr($form['#id'], 'marker')) {
    $form['#validate'][] = 'legume_marker_form_validate';
    
    // Change default value for submit button
    $form['submit']['#value'] = 'Search';
  }
} 


/**
  * Form validator for search form. 
  * Use this to trim whitespace from text fields.
  */
function legume_marker_form_validate($form, &$form_state) {
  if (isset($form_state['values']['marker_name']))
    $form_state['values']['marker_name'] = trim($form_state['values']['marker_name']);
}



